# https://travis-ci.org/sgelb/impositioner
dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
before_install:
  - pip install poetry
  - pip install pytype
install:
  - poetry install
script:
  - poetry run py.test
  - poetry run pytype impositioner
branches:
  only:
    - master
